### PR TITLE
proc_manager: refactor the sample publish procedure

### PR DESCRIPTION
**Pull request by uLipe**
by removing poll, process and fifo_get public functions and pack all those steps into a single function called step_pm_put(), this also limits the sample pool module responsibillity only to provide storage to the measurement data.

Signed-off-by: Felipe Neves <felipe.neves@linaro.org>

### CODE REVIEW

**Comment by uLipe** [comment]
It is WIP, needs to pass on the test suite and also needs to check if the current tests are good.

The new publish method simplified STeP a lot, and changed some responsibillities:

- Sample pool: should only provide storage to the measurements data;
- Processor manager: responsible to queue the samples and trigger the nodes
- Automatic poll: now this is a user responsibillity, the jusitification is located in the sampled data arrival rate, this rate should give the poll interval, as long the publishing method should trigger the nodes immediatelly.

**Comment by microbuilder** [comment]
> @microbuilder It is WIP, needs to pass on the test suite and also needs to check if the current tests are good.
> 
> The new publish method simplified STeP a lot, and changed some responsibillities:
> 
>     * Sample pool: should only provide storage to the measurements data;
> 
>     * Processor manager: responsible to queue the samples and trigger the nodes
> 
>     * Automatic poll: now this is a user responsibillity, the jusitification is located in the sampled data arrival rate, this rate should give the poll interval, as long the publishing method should trigger the nodes immediatelly.

We should generate new architectural diagrams in that case, to explain the basic design, replacing the images and draw.io source here: https://github.com/Linaro/step/tree/main/doc

I can make the images myself if you want to at least send over some napkin drawings, or ascii art with this PR.

**Comment by uLipe** [comment]
Test suite passed, I think due to simplification of the publish process the tests itself got more simple.

Regarding the drawings, okay, the overall architecture has not been changed too much, only the publish procedure, I will share the changes.

**Comment by uLipe** [comment]
[STeP achitecture simplfied.pdf](https://github.com/Linaro/step/files/9847667/STeP.achitecture.simplfied.pdf)

**Comment by uLipe** [comment]
@microbuilder PTAL.

I've put the relevant changed STeP simplfied architecture above, I don't have access to draw.io to edit the final drawing.

**Comment by uLipe** [comment]
@microbuilder now, all the documentation changes are in place, PTAL

**Review by microbuilder — APPROVED** [review]

**Pull request merged**
